---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-device-plugin
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app amd-device-plugin
  path: ./kubernetes/apps/kube-system/amd-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
    substituteFrom: []
  dependsOn:
    - name: node-feature-discovery-rules
