apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/prometheus-operator/kube-prometheus.git
  ref:
    branch: main
