---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./backube.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
  - ./prometheus-community.yaml
  - ./longhorn.yaml
  - ./piraeus.yaml
  - ./grafana.yaml
  - ./vector-charts.yaml
  - ./angelnu-charts.yaml
  - ./cloudnative-pg.yaml
  - ./spegel-org.yaml

