apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/agxOByuxZajpVeHKsJpvSeUnl+lPuYpVerI6IC+JcvIsXy0,iv:GYiCq4kexS6p6g+UEhQMCYSapw3/XoRNkGSjrJ3rYnA=,tag:22+6fNZKWdQSFMYoY2vv/A==,type:str]
    credentials.json: ENC[AES256_GCM,data:/ClLKe1cppTMUC0e1y4FwIE5jHse+lk5viIe4ktfvlIQDUkYHntzsKHQsHFAXJJPeV2UgmNaU48U8pP0KvDZKvnrveniEfiVLrdKf4GwCne4f1Oqno6/Q5WhhMtWEMVdzH4FtwIdSUAFuYXxzsjpx/nWXGbagBWF7nOEwOW/u+3hFyxS9vi5NWjWzpBxtjcGBmjaV8WTMqtc558009+GQLhp7FuKvpnrvqled/Yn8A==,iv:/rkknCxEYY7dL5XoMjKL1ycJUJ9ROPDy7oTZyOoZCdY=,tag:rm4EwuU8oxXP8kKaewLWUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV25uS3hoam1FZDNvVDJv
            ZWdmc3lSSFkzbng4a2tNTVhEeWJ5MnR2eUg0ClJNVUk5M0tMamZwSkN1OFJ6UjZw
            NkQ2SndpRHoyNC9KeEVlKzRwcXBveDAKLS0tIElPVjJvV28zUktiVGFabm1qNmJr
            VHRQeGNJQXR2WEUzVW0zbllVVkk0b2cKp7c2ULBjwnxYp3qdDLfq4/xzkFMeh2xt
            XM8MPeKpMJJhV6H8t5jS54+iDmoAq+tzeAs9oQbTeGuPmx3UxDyvSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T22:38:01Z"
    mac: ENC[AES256_GCM,data:J9SQ63lBig6VcPgd2PKUreqZMLFp9mrEXu/NJealQ95Fo6PtNWuSTIRhlhtoINUUrUZVsc+tXIFvXmBeqck1hT6UmbffeWrB4OeQ5JNJkIku5//3IEp33fltcJY0ZM+vbH1bd88nqRcnd0g0zXzVMe5uUkX7RtpDloppYn3iVkk=,iv:C8Qizsz+Aa3AJ4Gxj4FvGsj023v5zhlLHGiOTIUFOWo=,tag:fzYPlwnJWZJl0xHUyLGjHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
