---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gender2
spec:
  endpoints:
    - dnsName: "gender2.${SECRET_DOMAIN}."
      recordType: A
      targets:
        - 24.17.154.134
