apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: muse-storage
  name: muse-storage
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
