---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      forgejo-runner:
        replicas: 2
        initContainers:
          runner-register:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 5.0.2
            command:
              - "forgejo-runner"
              - "register"
              - "--no-interactive"
              - "--token"
              - $(RUNNER_TOKEN)
              - "--name"
              - $(RUNNER_NAME)
              - "--instance"
              - $(FORGEJO_INSTANCE_URL)
              - "--labels"
              - "docker:docker://ghcr.io/catthehacker/ubuntu:act-latest,x86_64:docker://ghcr.io/catthehacker/ubuntu:act-latest,linux:docker://ghcr.io/catthehacker/ubuntu:act-latest,pc:docker://ghcr.io/catthehacker/ubuntu:act-latest,ubuntu-x86_64:docker://ghcr.io/catthehacker/ubuntu:act-latest,linux:host"
            env:
              - name: RUNNER_NAME
                valueFrom:
                  secretKeyRef:
                    name: forgejo-runner-secret
                    key: RUNNER_NAME
              - name: RUNNER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: forgejo-runner-secret
                    key: RUNNER_TOKEN
              - name: FORGEJO_INSTANCE_URL
                valueFrom:
                  secretKeyRef:
                    name: forgejo-runner-secret
                    key: FORGEJO_INSTANCE_URL
        containers:
          daemon:
            image:
              repository: docker
              tag: 27.3.1-dind
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 5.0.2
            command:
              - "sh"
              - "-c"
              - "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; forgejo-runner --config /config/config.yml daemon"
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"
        annotations:
          reloader.stakater.com/auto: "true"
    service:
      app:
        controller: forgejo-runner
        ports:
          http:
            port: 45315
    persistence:
      docker-certs:
        type: emptyDir
        globalMounts:
          - path: /certs
      runner-data:
        type: emptyDir
        globalMounts:
          - path: /data
      config:
        type: configMap
        name: forgejo-runner-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
