apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml

configMapGenerator:
  - name: forgejo-runner-configmap
    files:
      - config.yml=./runner-config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
