apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:dZoneJhtVWmZV3X01gBLvEVFd7g11w0kwR1s,iv:LiXlriJOEGj1QOJjTOaOpa7Iiv2DJeeqmCABq3PtzVM=,tag:d/7iUO+kIkVzsauZ7B9kaw==,type:str]
    RUNNER_NAME: ENC[AES256_GCM,data:J6iOQwCrW+rOdLV+,iv:N7zDHVrjnb5BIRGextFAEhaWCxfR1sWlC2zUOVLYT6Q=,tag:evkJKONUedH7/jFiBNCD5Q==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:hhrqpbDv1chB738HPtJEWtwrEM9t8tNoxovJ/b85kq6evj/q7JcRTqf8Ow==,iv:JCEAqbdCJwYeo8CpCATYILlygcFiwKi8Gnk2+ZAPDgM=,tag:hXYfgM1bR2WMM28XCzZUiQ==,type:str]
    CACHE_SECRET: ENC[AES256_GCM,data:48W5K8MKGypt3VqZSoc+xy0no5KONYzT/SzXxZZt47SCbNLZcwsiRNvXAsDdbPcUghB7gTXL7CfEollOBAHAgw==,iv:LMzx22TihzIrIsE2zerKYPBmYN1fYSeLQhXfdcCUe/E=,tag:DeMTKgO26K86KXnUBiY9fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbytMaXZYamF4ekgxS3g2
            VmFqRjFlN3NseHRsMFI0WTNpbnR6VHFnOWgwCm9qYlp6d3hEc1ljSW1IODZRVXFK
            UU5pR0h0NG9TTGdnK2Zia2E2bFRLUncKLS0tIDRPcVlRdUc1RksrRXB1bWd3UGVx
            NnRkMERqU2MwRnI5dVlkczI1U0xLUDgKukSIiQXar3EPhPGYVschG9Ks4mHiuapZ
            d3LmfgbmNmcz1TDEN8ttQibZGCQ83P9Zat6MEAwvrrs418z36sCE0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T06:13:10Z"
    mac: ENC[AES256_GCM,data:eo7wbp4yVgesdpVQw5OMOUBdmGavRtVI9iKaEmkhFUOmMN28kQxmse2WsTaDIB+WMk6dL1/Y/P5aTGO1uuFjP5eeG5eS2FR1AO+3cw64O8c4u+4otDHcMEYzdrReo7AwBMgP0SvHSF7n9+d9oe7Ll1hmq+p4WminT6iK1dyPN2Y=,iv:SXiZYGiB3CDW9t95kfr3yaauArFt1Vlhd4EJ2VjrKBk=,tag:7vZnMhXLpF8619cWDX+GgQ==,type:str]
    version: 3.13.3
