apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
type: Opaque
stringData:
    FORGEJO_INSTANCE_URL: ENC[AES256_GCM,data:dZoneJhtVWmZV3X01gBLvEVFd7g11w0kwR1s,iv:LiXlriJOEGj1QOJjTOaOpa7Iiv2DJeeqmCABq3PtzVM=,tag:d/7iUO+kIkVzsauZ7B9kaw==,type:str]
    RUNNER_NAME: ENC[AES256_GCM,data:J6iOQwCrW+rOdLV+,iv:N7zDHVrjnb5BIRGextFAEhaWCxfR1sWlC2zUOVLYT6Q=,tag:evkJKONUedH7/jFiBNCD5Q==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:hhrqpbDv1chB738HPtJEWtwrEM9t8tNoxovJ/b85kq6evj/q7JcRTqf8Ow==,iv:JCEAqbdCJwYeo8CpCATYILlygcFiwKi8Gnk2+ZAPDgM=,tag:hXYfgM1bR2WMM28XCzZUiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbytMaXZYamF4ekgxS3g2
            VmFqRjFlN3NseHRsMFI0WTNpbnR6VHFnOWgwCm9qYlp6d3hEc1ljSW1IODZRVXFK
            UU5pR0h0NG9TTGdnK2Zia2E2bFRLUncKLS0tIDRPcVlRdUc1RksrRXB1bWd3UGVx
            NnRkMERqU2MwRnI5dVlkczI1U0xLUDgKukSIiQXar3EPhPGYVschG9Ks4mHiuapZ
            d3LmfgbmNmcz1TDEN8ttQibZGCQ83P9Zat6MEAwvrrs418z36sCE0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T04:48:47Z"
    mac: ENC[AES256_GCM,data:0lnRaQW1eZJounYk3EqhobMNfLbcT5xCahXezcomEHc9vzTJrncOLH2SBC37Y7tZKBHboIAuL2gBgogptgfOyQ0pDWILL5/yN0Tq7476ueRq1hmdscae4NdwuUB1OFUttdMSjwlTwhXFlk8Gadv60BIv/dpBjxuG6Za8JHqgDYY=,iv:fMB34FHNmHL0wetaBkI/g7S7ZGlf23C6ava6KXXi5gg=,tag:Ek9KPK4nyeRo1bX50nwKGg==,type:str]
    version: 3.13.3
