apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:+VdK1KPEy/fxV8HHwc1yy/L9TltLLb/ZwflXZKEe4B/oI88+0YmLdA==,iv:VmuRR4KL8rGGICrcVWUnq5YYCLC4o1cE4mBusnmUZVM=,tag:sb3RJO4n9qF4Ys1Kk9B01w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Q0c4VU5JSWp4L2xObERn
            ay9oTGVEY29FRDNkZUp0KzNWQVVzZFZUaXhZClA0dWFqL2YrUEdDakQ3SzdEbDhB
            OUJsN01aMTUwSFduYzl0RkZrZHRJb1UKLS0tIEJkN3lWb0M0SE1lV0xXa0t0OGpr
            TkZLLzJWY2lRVW0zQzA3em9sb3ZuTDQKjoTWgp3S+07TMz19Fsylrt7HWuOAwVY8
            j6L/oNhIcVdZZ8gDDi0sjdCjCAAnXKL8LGpW9vC/OwnNVDZxRZY0eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T02:37:01Z"
    mac: ENC[AES256_GCM,data:QYKcMoM6oRSwas7jv0gHUPBr3AVCODxpcGdfsdcZ2fiFUASGwastiVXYBtmzgVGuz1OSKCbj01ax45NQkCumdyyEzhvXK3qnYQHJtdac45XBTIjiZcgwWVgahzOJYJg0Wqol5IMs89UfVi9eyIBeogcePKCOiGNFZsdWpzr8GUM=,iv:nFRzyjgFzyo+ghsl/MfH7NcM/hXXjUrXSsNWXSXC2R8=,tag:ci+b61entNDEP9TMbD8eNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
