---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
defaultPodOptions:
  enableServiceLinks: true
  securityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 65539

controllers:
  rdio: # this can now be any name you wish
    containers:
      app: # this can now be any name you wish
        image:
          repository: ghcr.io/usa-reddragon/rdio-scanner
          tag: v7.2.18
          pullPolicy: IfNotPresent

        probes:
          liveness:
            custom: true
            type: HTTP
            spec:
              path: /
              port: http
          readiness:
            custom: true
            type: HTTP
            spec:
              path: /
              port: http

        resources:
          limits:
            cpu: 250m
            memory: 150Mi
          requests:
            cpu: 150m
            memory: 100Mi

        env:
          - name: TZ
            value: America/Los_Angeles
          - name: METRICS_PORT
            value: '9108'
          - name: DB_HOST
            value: postgres16-rw.database.svc.cluster.local
          - name: DB_TYPE
            value: postgresql
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: rdio
          # - name: DB_SSLMODE
          #   value: "require"
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: rdio-pg-cluster-app
                key: password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: rdio-pg-cluster-app
                key: username

service:
  rdio: # this can now be any name you wish
    controller: rdio
    ports:
      http:
        port: 3000
      metrics:
        port: 9108

ingress:
  media: # this can now be any name you wish
    className: external
    hosts:
      - host: &host rdio.${SECRET_DOMAIN}
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host

serviceMonitor:
  rdio:
    serviceName: rdio
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        scrapeTimeout: 3s
        interval: 10s

