---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rdio
  namespace: default
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    # defaultPodOptions:
    #   enableServiceLinks: true
    #   securityContext:
    #     runAsUser: 568
    #     runAsGroup: 568
    #     fsGroup: 568
    #     fsGroupChangePolicy: "OnRootMismatch"
    #     supplementalGroups:
    #       - 65539

    controllers:
      rdio: # this can now be any name you wish
        annotations:
          secret.reloader.stakater.com/reload: "rdio-config"
        containers:
          app: # this can now be any name you wish
            image:
              repository: docker.io/chuot/rdio-scanner
              tag: latest@sha256:aa3bd0b5137580e813836f7e0705af7d66412a28bc73f912c95eacbe70bcd4ef
              pullPolicy: IfNotPresent

            command: ["./rdio-scanner"]
            args: ["-base_dir", "/app/data", "-config", "/config/rdio-scanner.ini", "-db_pass", "$(DB_PASS)"]

            probes:
              liveness:
                custom: true
                type: HTTP
                spec:
                  path: /
                  port: http
              readiness:
                custom: true
                type: HTTP
                spec:
                  path: /
                  port: http

            resources:
              limits:
                cpu: 1000m
                memory: 250Mi
              requests:
                cpu: 200m
                memory: 100Mi

            env:
              - name: TZ
                value: America/Los_Angeles
              # - name: METRICS_PORT
              #   value: '9108'
              # - name: DB_HOST
              #   valueFrom:
              #     secretKeyRef:
              #       name: rdio-pg-cluster-app
              #       key: host
              # - name: DB_TYPE
              #   value: postgresql
              # - name: DB_PORT
              #   valueFrom:
              #     secretKeyRef:
              #       name: rdio-pg-cluster-app
              #       key: port
              # - name: DB_NAME
              #   valueFrom:
              #     secretKeyRef:
              #       name: rdio-pg-cluster-app
              #       key: dbname
              # # - name: DB_SSLMODE
              # #   value: "require"
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: moco-rdio-moco-v3
                    key: WRITABLE_PASSWORD
              # - name: DB_USER
              #   valueFrom:
              #     secretKeyRef:
              #       name: rdio-pg-cluster-app
              #       key: username

    service:
      rdio: # this can now be any name you wish
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "10.10.10.34"
        labels:
          io.cilium/l2: "true"
        controller: rdio
        ports:
          http:
            port: 3000
          # metrics:
          #   port: 9108



    ingress:
      media: # this can now be any name you wish
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host rdio.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: rdio
                  port: http
        tls:
          - hosts:
              - *host

    # serviceMonitor:
    #   rdio:
    #     serviceName: rdio
    #     endpoints:
    #       - port: metrics
    #         scheme: http
    #         path: /metrics
    #         scrapeTimeout: 3s
    #         interval: 10s

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: "/app/data"
            readOnly: false
      config:
        type: secret
        name: rdio-config


