apiVersion: v1
kind: Secret
metadata:
    name: rdio-config
type: Opaque
stringData:
    rdio-scanner.ini: ENC[AES256_GCM,data:vdnxmT6SG6ryLRh8UipIdsm/moWV57xYmZGjhSaICZNBJD2AWy6Zi6GWzWLGOCyR72PY9vCk6+twBk1OGBbMGThDB45f825iKnIaMJI5ouqRGDnIY84FyvwP0AAAM0Npy5GA46yflkp5GxIGIaQaC7OjQepLwsou8D/86A7PTA==,iv:eiLyAZdJNpT2OTUnOckJYbKOdx3HPG8cCw1YeJ0fLpA=,tag:JWG64c7nOdPsXdDDnTqvWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN0R2VGVvSEZQTFk1ZzJ2
            SVRzQUQzUEpiSXpqZDRmQ2lOOW5mVXp6aHprCkQzT2NEVWd6OExSVXAzTTZQZndP
            cVJ1NXYyeDVaOFlnRTl0K3ZrYlZmRkEKLS0tIDN5VktMVEdzdUcvMWV0Vys4c1NE
            UVJ6Tm4ydC9ncCtNTyt1TGJKUW5ETUUKrj/5V4/DGOaDcm+1r66oSAmy+NInMchH
            DSB3fq5pCryl6rEM9mWEPvpVbaUB2QPZQ6vuvpr/ycs03xwc8ykAqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T04:57:00Z"
    mac: ENC[AES256_GCM,data:+W5rgXQtNzyEgiXlzomKS6yLNIKV58eSikmbxo8skriv171kmiF9cNBzoqZQlsxRu4zQLPXEiRxSU+XC46cBPhFeLU8o2PmfkdBiBYiWGP6GdlhFbETEUf57TneD6wOY5QlxnIMV1kGUmPYsqqs+P21nYPxe0uOHlSc2ABnPQbI=,iv:rwz9UB8bxabyJWcq3wNoVprRhbBs2fEpouqcx3Uj4d8=,tag:55ppArBORVqpHB/Amajf3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
