---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app loki
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/monitoring/loki/app
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: longhorn
  decryption:
    provider: sops
    secretRef:
      name: sops-age
