---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app vector-aggregator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vector-aggregator:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-geoip:
            image:
              repository: ghcr.io/maxmind/geoipupdate
              tag: v6.1.0@sha256:cdd36d36c2e1d353a990a48e5a36d42ee75089d5d9064d80d36d90c147fd2606
            env:
              GEOIPUPDATE_EDITION_IDS: GeoLite2-City
              GEOIPUPDATE_FREQUENCY: "0"
              GEOIPUPDATE_VERBOSE: "true"
            envFrom:
              - secretRef:
                  name: vector-aggregator-secret
        containers:
          app:
            image:
              repository: docker.io/timberio/vector
              tag: 0.37.0-alpine@sha256:f0645334e82d9bfa45d79899ec1c84ccbd54c1acdce21c8e7797fc15758a197a
            args: ["--config", "/etc/vector/vector.yaml"]
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      vector-aggregator:
        controller: vector-aggregator
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.10.30
        labels:
          io.cilium/l2: "true"
        ports:
          http:
            primary: true
            port: 8686
          kubernetes-logs:
            port: 6000
          journald:
            port: 6001
          talos-kernel:
            port: 6050
          talos-service:
            port: 6051
    persistence:
      config:
        type: configMap
        name: vector-aggregator-configmap
        globalMounts:
          - path: /etc/vector/vector.yaml
            subPath: vector.yaml
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /vector-data-dir
      geoip:
        type: emptyDir
        globalMounts:
          - path: /usr/share/GeoIP
