---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rdio-pg-cluster
spec:
  instances: 3 # set to the number of nodes in the cluster
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2-10
  primaryUpdateStrategy: unsupervised
  storage:
    size: 30Gi
    storageClass: openebs-hostpath
  # superuserSecret:
  #   name: cloudnative-pg-secret
  # enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
    # # Ref: https://github.com/cloudnative-pg/cloudnative-pg/issues/2501
    # podMonitorMetricRelabelings:
    #   - { sourceLabels: ["cluster"], targetLabel: cnpg_cluster, action: replace }
    #   - { regex: cluster, action: labeldrop }
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://rdio-db-backup/
      endpointURL: https://s3.cleeb.net
      # Note: serverName version needs to be inclemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster rdio-pg-cluster-v0
      s3Credentials:
        accessKeyId:
          name: rdio-pg-cluster-secret
          key: minio-user
        secretAccessKey:
          name: rdio-pg-cluster-secret
          key: minio-pass
  # # Note: previousCluster needs to be set to the name of the previous
  # # cluster when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v0
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *previousCluster
