apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  namespace: default
  name: rdio-moco-v3
spec:
  # replicas is the number of mysqld Pods.  The default is 1.
  # You can only increase the number of instances in a MySQLCluster from 1 to 3 or 5, or from 3 to 5.
  # Decreasing the number of instances is not allowed.
  replicas: 1

  backupPolicyName: daily
  serverIDBase: 1
  podTemplate:
    spec:

      # Make the data directory writable. If moco-init fails with "Permission denied", uncomment the following settings.
      # securityContext:
      #   fsGroup: 10000
      #   fsGroupChangePolicy: "OnRootMismatch"  # available since k8s 1.20
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mysql
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - rdio-moco-v3
            topologyKey: "kubernetes.io/hostname"

      containers:
      # At least a container named "mysqld" must be defined.
      - name: mysqld
        image: ghcr.io/cybozu-go/moco/mysql:8.4.2
        # By limiting CPU and memory, Pods will have Guaranteed QoS class.
        # requests can be omitted; it will be set to the same value as limits.
        resources:
          limits:
            cpu: "1"
            memory: "8Gi"

  volumeClaimTemplates:
  # At least a PVC named "mysql-data" must be defined.
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 50Gi

  # restore field is not editable.
  # to modify parameters, delete and re-create MySQLCluster.
  restore:
    # The source MySQLCluster's name and namespace
    sourceName: rdio-moco-v2
    sourceNamespace: default

    # The restore point-in-time in RFC3339 format.
    restorePoint: "2024-08-23T18:00:00Z"

    # jobConfig is the same in BackupPolicy
    jobConfig:
      serviceAccountName: default

      bucketConfig:
        bucketName: "moco"
        endpointURL: https://s3.cleeb.net
        usePathStyle: true
        region: us-east-1
      envFrom:
      - secretRef:
          name: rdio-cluster-secret
      workVolume:
        emptyDir: {}

