apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdio-cluster-daily-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 32Gi
