apiVersion: v1
kind: Secret
metadata:
    name: rdio-pg-cluster-secret
    labels:
        cnpg.io/reload: ""
type: Opaque
stringData:
    minio-user: ENC[AES256_GCM,data:39VW+2Q+i3wCpQ==,iv:0P7D2iJGc2O6wf8c3t6m6e7SnD4fa1JmcccEvA96ypc=,tag:PT3WkkIgjDaRQ7JmTdUxuA==,type:str]
    minio-pass: ENC[AES256_GCM,data:1yzov01N4XoLHPsRdGSdQqOM0OJcFq8IsFac2g==,iv:B+pLs65/hSFDDR90OiRjQqS5Fs4+gxndr0CA3KGBfU8=,tag:EurrBs6a9LUjfq/socZ++Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYStRY28wckVPN3BSaER6
            ZTVWRDV6QVE4blhqT3F2dE9IVUJFSzlSRHdJCm1rQzE5c2JkTVE0VDVkOTNEU2lO
            aXpJWTZ1UXltK0lLR2J0N2JQK2NPNTQKLS0tIGQzZm41c0xreWdBZEt5MnpRdnhw
            dHVzWFhCeFRoY0ZrQkFrWk8xVDBIa3cKMPPfjXd6PfqTWANfZUYyyTT9AUvnIzo6
            5ff6txp7swnESuQYRCQJnDIJkXYuXux8N3N3XDDEbeBkMYVmwmO9Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T22:22:48Z"
    mac: ENC[AES256_GCM,data:QVB7oRmGNBgGisWHqBYrKw9Am0O+y2+8H6G18XL5noDz+EyJuW4QuuBrMtQ3LGIEHko5bF7BG3/EIGGkl/NkBjURZkFgHvtHdcww/a6ZdMn2ot00UZG3kdLrN2LZri74b08hgUMl3bGfkW3HC6XtKOL/tjGf2di4CFaDT2fzVcU=,iv:m4pWiUnQKruOHjZuFHKopGcfP2zBKsFettnpv2EZewI=,tag:5e/1aDKipGxJr06/fI35wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
