apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moco-daily-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 20Gi
