---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vidifier
  namespace: downloads
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  values:
    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 65539
      labels:
        setGateway: "true"
      annotations:
        setGateway: "true"

    controllers:
      vidifier:
        annotations:
          reloader.stakater.com/auto: "true"
          setGateway: "true"
        labels:
          setGateway: "true"
        containers:
          app: # this can now be any name you wish
            image:
              repository: ghcr.io/cschmittiey/vidifierbot
              tag: 0.6.4
              pullPolicy: IfNotPresent

            resources:
              limits:
                cpu: 1000m
                memory: 1G
              requests:
                cpu: 5m
                memory: 100Mi

            env:
              - name: TZ
                value: America/Los_Angeles


    # service:
    #   vidifier: # this can now be any name you wish
    #     type: LoadBalancer
    #     externalTrafficPolicy: Cluster
    #     annotations:
    #       io.cilium/lb-ipam-ips: "10.10.10.34"
    #     labels:
    #       io.cilium/l2: "true"
    #     controller: vidifier
    #     ports:
    #       http:
    #         port: 3000
    #       # metrics:
    #       #   port: 9108



    # ingress:
    #   media: # this can now be any name you wish
    #     className: external
    #     annotations:
    #       external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    #     hosts:
    #       - host: &host vidifier.${SECRET_DOMAIN}
    #         paths:
    #           - path: /
    #             service:
    #               identifier: vidifier
    #               port: http
    #     tls:
    #       - hosts:
    #           - *host

    # serviceMonitor:
    #   vidifier:
    #     serviceName: vidifier
    #     endpoints:
    #       - port: metrics
    #         scheme: http
    #         path: /metrics
    #         scrapeTimeout: 3s
    #         interval: 10s

    persistence:
      config:
        type: secret
        name: vidifier-secret
        globalMounts:
          - path: /app/data
            readOnly: true
      local:
        type: emptyDir
        globalMounts:
          - path: /.local
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp


