apiVersion: v1
kind: Secret
metadata:
    name: onedev
    labels:
        cnpg.io/reload: ""
type: Opaque
stringData:
    minio-user: ENC[AES256_GCM,data:1DtDehVWSjccx80MXSBOxpVLCUYxAhJ19N8=,iv:d8pFSODCZLOwyA0yBvoRafqv8hP6CiZI+XY/Vm/XRoM=,tag:1Ca/5w5/yE9NgV9aTaWqBw==,type:str]
    minio-pass: ENC[AES256_GCM,data:3Oti81/Ckj3NSitK06Az/xUvZ6mmZNtHd7ZMmYk3uflMGZoqlwdyHONgfhQ168KXqLUtgLpF0czPk8VUF3JkTQ==,iv:E4jRYf8ucT6dg3HMOG89Hp3NwLnKXKPGVhTwZs3P9WQ=,tag:CCfxGarkIsfl41TyFbkvQA==,type:str]
    region: ENC[AES256_GCM,data:aENphoab,iv:F5DseNrZkOeJCkWchV4G1LTj3Q6wJiHo7lg2+CorCF0=,tag:BYVW5fVVQm04S5Cs5IhEgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YVVkdEZYaFFhUEE2a0E0
            ZTdBQjVsdGhHZ1BVVUZhREtremxOeHFwMW1nCmZ2S05wZDEzVEpPd2dQSCt5aHJI
            OFVwdlAvOWtTNCtBQ2ZuQmxwUVhRTFEKLS0tIHNzY1gvcWpDRk1zRkE1UXpNeDFm
            Rk1wNU80Qmw4VnNRTTAvZ2c4QjRMdWsKe/L/gdPIrljl9qjhVrWpXbaba4Jl4Bs8
            4ONkG4npHNSQbzxDbb5IcpWIohOFpVI6SUTBOzvl5ID80qBPtv5cQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T10:48:27Z"
    mac: ENC[AES256_GCM,data:2W/tdnRQDqNxD6SXCsXhn/PGosbATvIjZVem1h+VuF1DlLyJ8bdDVbZe2rD6H5EfOLhy8quzBOmOSVAXVimrDOH3aiuSLk2/tBJh1ehb8e4RRJMqQHHAAV4J1Tvg9vI9rkJHMFbmdbnAXvpidkqkQ0eX7Y28tLtx/aKtGm3qx2M=,iv:+o/DeSMfehyLPWmLsZWUlmYLV+9FOTaoHC+TthWYD8s=,tag:k+z2KWoHYd1SYv6rTnB/nw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onedev-db-owner
    labels:
        cnpg.io/reload: ""
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:V0b1vGs1,iv:dUk09E4etysdx7GGt9zc6wP7NaSf67j9IyX8HPGDYrM=,tag:tKm8a2xEytv7qyi0WuxScg==,type:str]
    password: ENC[AES256_GCM,data:aCL4/KxPWG/xQ0YPa7KXZKDfxsQNK/0O6VoTMPszL+o=,iv:QDIugZMOqO8f9vhBR/P5tMEEORawRC+njsNQlEXcAas=,tag:RXGXsFwPg7WlFbBJg2u92A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YVVkdEZYaFFhUEE2a0E0
            ZTdBQjVsdGhHZ1BVVUZhREtremxOeHFwMW1nCmZ2S05wZDEzVEpPd2dQSCt5aHJI
            OFVwdlAvOWtTNCtBQ2ZuQmxwUVhRTFEKLS0tIHNzY1gvcWpDRk1zRkE1UXpNeDFm
            Rk1wNU80Qmw4VnNRTTAvZ2c4QjRMdWsKe/L/gdPIrljl9qjhVrWpXbaba4Jl4Bs8
            4ONkG4npHNSQbzxDbb5IcpWIohOFpVI6SUTBOzvl5ID80qBPtv5cQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T10:48:27Z"
    mac: ENC[AES256_GCM,data:2W/tdnRQDqNxD6SXCsXhn/PGosbATvIjZVem1h+VuF1DlLyJ8bdDVbZe2rD6H5EfOLhy8quzBOmOSVAXVimrDOH3aiuSLk2/tBJh1ehb8e4RRJMqQHHAAV4J1Tvg9vI9rkJHMFbmdbnAXvpidkqkQ0eX7Y28tLtx/aKtGm3qx2M=,iv:+o/DeSMfehyLPWmLsZWUlmYLV+9FOTaoHC+TthWYD8s=,tag:k+z2KWoHYd1SYv6rTnB/nw==,type:str]
    version: 3.13.3
