---
data_dir: /vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686

enrichment_tables:
  geoip_table:
    type: mmdb
    path: /usr/share/GeoIP/GeoLite2-City.mmdb

#
# Sources
#

sources:
  journald_source:
    type: vector
    version: "2"
    address: 0.0.0.0:6000

  kubernetes_source:
    type: vector
    version: "2"
    address: 0.0.0.0:6010

  talos_kernel_source:
    address: 0.0.0.0:6020
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host

  talos_service_source:
    address: 0.0.0.0:6030
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host

#
# Transforms
#

transforms:
  kubernetes_remap:
    type: remap
    inputs: ["kubernetes_source"]
    source: |
      # Standardize 'app' index
      .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"


  talos_kernel_logs_xform:
    type: remap
    inputs:
      - talos_kernel_source
    source: |-
      .__host, err= replace(.__host, "10.10.10.100", "mercury")
      .__host = replace(.__host, "10.10.10.101", "venus")
      .__host = replace(.__host, "10.10.10.102", "earth")
  talos_service_logs_xform:
    type: remap
    inputs:
      - talos_service_source
    source: |-
      .__host, err = replace(.__host, "10.10.10.100", "mercury")
      .__host = replace(.__host, "10.10.10.101", "venus")
      .__host = replace(.__host, "10.10.10.102", "earth")

#
# Sinks
#

sinks:
  journald:
    inputs: ["journald_source"]
    type: loki
    endpoint: http://loki-gateway.observability.svc.cluster.local
    encoding: { codec: json }
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      hostname: '{{ host }}'

  kubernetes:
    inputs: ["kubernetes_remap"]
    type: loki
    endpoint: http://loki-gateway.monitoring.svc.cluster.local
    encoding: { codec: json }
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      k8s_app: '{{ custom_app_name }}'
      k8s_container: '{{ container_name }}'
      k8s_filename: '{{ file }}'
      k8s_instance: '{{ pod_labels."app.kubernetes.io/instance" }}'
      k8s_namespace: '{{ kubernetes.pod_namespace }}'
      k8s_node: '{{ kubernetes.pod_node_name }}'
      k8s_pod: '{{ pod_name }}'

  talos_kernel:
    type: loki
    inputs:
      - talos_kernel_logs_xform
    endpoint: http://loki-gateway.monitoring.svc.cluster.local:80
    encoding:
      codec: json
      except_fields:
        - __host
    batch:
      max_bytes: 1048576
    out_of_order_action: rewrite_timestamp
    labels:
      hostname: '{{ __host }}'
      service: '{{ facility }}'

  talos_service:
    type: loki
    inputs:
      - talos_service_logs_xform
    endpoint: http://loki-gateway.monitoring.svc.cluster.local:80
    encoding:
      codec: json
      except_fields:
        - __host
    batch:
      max_bytes: 524288
    out_of_order_action: rewrite_timestamp
    labels:
      hostname: '{{ __host }}'
      talos_service: '{{ talos-service }}'
      namespace: "talos:service"
