---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app downloads-gateway
  namespace: network
spec:
  chart:
    spec:
      chart: pod-gateway
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      version: 6.5.1
  interval: 15m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181
    DNS: 172.16.1.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            # TODO: Replace with ghcr.io/qdm12/gluetun when a versioned tag is available
            repository: docker.io/qmcgaw/gluetun
            tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
        env:
          - name: VPN_SERVICE_PROVIDER
            value: airvpn
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT
            value: "off"
          - name: DOT
            value: "off"
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 30s
          - name: SERVER_COUNTRIES
            value: United States
          - name: FIREWALL_VPN_INPUT_PORTS
            value: 1637,28163
        envFrom:
        - secretRef:
            name: downloads-gateway

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          enabled: false # Using my own Cilium-based Network Policies

      netshoot:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app

    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: 28163
            type: udp
          - port: 28163
            type: tcp

    routed_namespaces:
      - downloads

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "1637"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5
      namespaceSelector:
        label: downloads-routed-gateway
      podAnnotations:
        configmap.reloader.stakater.com/reload: downloads-gateway-pod-gateway,downloads-gateway-pod-gateway-addon-vpn
        secret.reloader.stakater.com/reload: downloads-gateway
