---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app downloads-gateway
  namespace: network
spec:
  chart:
    spec:
      chart: pod-gateway
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      version: 6.5.1
  interval: 15m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.11.1@sha256:0617304f085bc98529f0c5cd0c40c63bb019380a026a277c812bd13f78b4bc5d
    DNS: 172.16.1.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            # TODO: Replace with ghcr.io/qdm12/gluetun when a versioned tag is available
            repository: docker.io/qmcgaw/gluetun
            tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
        env:
          - name: VPN_SERVICE_PROVIDER
            value: airvpn
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT
            value: "off"
          - name: DOT
            value: "off"
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 30s
          - name: SERVER_COUNTRIES
            value: United States
          - name: FIREWALL_VPN_INPUT_PORTS
            value: 1637,28163
        envFrom:
        - secretRef:
            name: downloads-gateway
        resources:
          limits:
            kernel.org/tun: 1

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          enabled: false # Using my own Cilium-based Network Policies

      netshoot:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app

    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: 28163
            type: udp
          - port: 28163
            type: tcp

    routed_namespaces:
      - downloads

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "1637"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.11.0@sha256:63216984df3bb257cdb4dc888cdb50175f91637b0bee041e670bdc0e275cd5af
      namespaceSelector:
        label: downloads-routed-gateway
      podAnnotations:
        configmap.reloader.stakater.com/reload: downloads-gateway-pod-gateway,downloads-gateway-pod-gateway-addon-vpn
        secret.reloader.stakater.com/reload: downloads-gateway
