apiVersion: v1
kind: Secret
metadata:
    name: firecrawl
    labels:
        cnpg.io/reload: ""
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:teFL43Kpqt3x,iv:iSZtM6z1Qb9Z/BGVX7rgsURzLxhxvdFq2WsWkdII5B4=,tag:p0peFdw1WEUWYhStS+ZVxA==,type:str]
    password: ENC[AES256_GCM,data:xS+O28UFdZFaB8ACRPS99cbYJyU3O1AYnOFIomeh5/tuYd/xNi+nURasulZb4xdK2iadB1SZxdneIk1tlj0Z3w==,iv:Z3UpTiRfrGSDw06ezSDDFrkzVwcPgMPy7XCuSq9v764=,tag:gTa8hE82+eDbcmqE9HgSDA==,type:str]
    redis-password: ENC[AES256_GCM,data:/MyER9QkLP+kw3V3HsIWD973Wgkm8ShSk5acZI9r/MdMReSi1l82Qs5OvKI7i7dipa/TfUf0vddeLjnGqmz77g==,iv:wefSz35h+wq6SDYYRjr3fQH2p6GjiT+xOvKhzGYLvSE=,tag:4TthqF3SUoJP9FSFqw3Zpw==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:7fUW8yX9ns+NkcrOkUgpQPztcePwtzEmkcr7N9PGUAztPkXXW3vu9qaCJ5fccQHHIrZD1o6MOUT/iAmuAq8jow==,iv:CgyAwi31R2W2JUeRPZAV29AMmjogNyDsr1KMj2npPrM=,tag:7lYWmJghJfbFL9XAOoE13g==,type:str]
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:qN1f/13gEaTIDuyM5sR0da3IsK8l9k8jdarNekuFEZlvZtKJU29MfuSyJFumFVadxYJ5+n6NZHqoUBxoh2Rm/w==,iv:NlO41f3OKus2GJ+0uxsAssR0BthN0HpQPOZQf+hMKzc=,tag:Hol6VRCULQqIs1/4GndNOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcXZTWEREdU9waHBjdUx1
            NzFwaktmTXJkVUZhbHhsSWxjd2VDUGsvRWp3CkQwWWJpa1VwWTFySmRwbGZoUlkw
            OUtPOXdZMzFjVHJZYXhBeEY1WmkwaTgKLS0tIFVmbGtIN0JtQ2I4aFhzZEgyNVlP
            YlVTbmoyZTlpYjZMZnRNMFhrQzRRNTAKunrKDIUInkqNxKK4zm/CO0UVPx1KBdaC
            zOfKwuklbXOQbhtNeAbhHODQJofb+Du1EI+uV5DoV69WRS0v1Mh4jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T00:48:36Z"
    mac: ENC[AES256_GCM,data:f3Bgeub+/jpaEVpmpOgq5nzrpeZSLRkcrwx8LC1TsxRsssfMrmo+/80o6hSrJ7C4/M+sWMaLOo4++ikc445YkdJBMaYxF2bOuONJ4no5JuBYk3BDncDocyuXWu0pClxOuWSb9GAvwcwZX5fniBPyWaQOmstQrTkXv84N+Z7D3o0=,iv:m9cqb8EEwNlxTxtPjOXKFU1H1dq4Qq4SSvv/RD3evNo=,tag:ifirn4GnEYs0zwTl+/zZYw==,type:str]
    version: 3.13.3
