apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Gll73Sy/8HSvAJHQ,iv:sRi8vinCHGFvy7oli++QlIVZtyzzkBAL0tQ2gG7eksw=,tag:waoezso9l9OQ/3vxJm+LwQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZdTqJTnrN5FC6df0Uc9P,iv:qEMj8SY9gnRL/E0cFQzsEG5Pgbm2oGp8C+d7Iy8his8=,tag:jZbql4rsPM9/XB/77UgePw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qn822l7uxTzgVZGfdGdJlZLxGESUEa2kdQB9jK1wt0wgq/K/,iv:qUPPDaedjca6RqipRQxH7G7f8LhfHEbKm2UnxvgwGoc=,tag:FEj1E6xchYzqzMJFSb8QkQ==,type:str]
    #ENC[AES256_GCM,data:1I5LTcA=,iv:s8jLV/UZMye79raa/HmrP+VuL2OJU5C2qJUv5eoUTHw=,tag:dHuRzjFIZO33Jr8uBX5EKg==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Y27sL6sYtvV+4A==,iv:ZBtThPu9v2jzznn3UJfNXfnTCwn10XeScmoPC0n4KZ8=,tag:IWAx6qCUEhZ2OOPx5QHvpw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:cmeXxUCzeBlCzxjIUtXbCN7IyM8dNg8Ye4jzgQ==,iv:Z/gKTQPnDTh+gSdRYJGjHyAnO/izPgg51k2yiu9gKLU=,tag:JahxsNSXu2wLXnHAp5Pn7w==,type:str]
    #ENC[AES256_GCM,data:GSULgT1v,iv:JYSSqZ4tvwOjksDY748Uc3aCWti2RhtPD2haHJTEUqk=,tag:eGPu/XJQ3MRO+/FfMDA+IQ==,type:comment]
    RESTIC_PASS: ENC[AES256_GCM,data:1rwv2EuoP5QTiSHMplnOj/K9L1qTy0mZb9ooJYtOlBV4vw8vAkme9UfE4kd4PU0o5bUwAn97wbEFJC1BrHYa,iv:gUUUZUPkL2Ti0LNudg2FsdrEAFvPTqkdyQaTT9Vc9jY=,tag:7bCkQUVvP+CWbnZzyXF9OA==,type:str]
    REPO_TEMPLATE: ENC[AES256_GCM,data:lqWQMc+HdXDDv++akJyN1zF8yTTXHC8aLIIbmdq8McfgFV4=,iv:3ATZ0To84M0elPkSXBmZkhZSa4ZRTh6mlrIb+KM/d94=,tag:0yv9oVg5nGhjo9AJ4EfN8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTVExMWFXS2RnQlE1aGl2
            cHBTaUs1bUlpUGtXSFMrcHhVSm9LOTVkdUVzCnNCaGR1YVJsTVlsUVJQQVJMemVn
            WmpNM3M2dHpyZ1k2TVROSUVBQU5Xd00KLS0tIEx0OVhLeVVMUFVNVmpMUnZDNTEz
            ZThnRytzemdPZ2VYdldnV1BFcm12czQK3/KpeNUeGZjBXhJUgXJwC1uD7HOB9MG5
            Pvv1LBzJwYqnkq8+9n+dcHW1ts42UcDGs/koAc7PIT/zd/tJx1GO4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T06:57:32Z"
    mac: ENC[AES256_GCM,data:na1Vsdb8dLKr6LqG5I7snp627K6/sD3Rkx98FLtW+Dpd2j3fekfzReUoInVhoI/CaCYAnW8TEWbhSQPNDEb6PJeX9qMqV/i7VQs01BfzcXykPNz6XA2ZuKCB9mtyGhBE3kfC13wG2b0Wfs1R2JirLYNAp7fSMOgcH4OrHHx48Pw=,iv:pfMhmVKxSRM1QKvlCjoTMWCJEpStclhBQGKVdYK8Agc=,tag:4tfOAgOThfvOyqBWLZYlpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
