---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  CLUSTER_CIDR: "10.24.0.0/16"
  NODE_CIDR: "10.10.10.0/24"
  CLUSTER_NAME: "sol"
  VOLSYNC_VOLUMESNAPSHOTCLASS: longhorn-snapshot-vsc
  VOLSYNC_CACHESTORAGECLASS: longhorn
  VOLSYNC_STORAGECLASS: longhorn
