apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:9CIqmxiGMs/8zQWUuuEOrAPAj9/xZJGMTZDO9zcJxq6YXV2htDCLicrLnwteIJk97sMML0Wvz83dDhD8xt2yiEdaRjhfbrUyRrIrgT223TIDoW6kzQpVMMAi/RjbQA==,iv:MFOAF51lGTH3kRA3wE+aMcAjdsi/CLAfDhb0xhy1PGk=,tag:7hT0ANpEKI6/lGWyCBNNVQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:089BPtiIjDo2,iv:h6QVQ9CkGb5QMztiY5K7OdLJlm6aBGm5slsvbwcuJZ4=,tag:GhQOmVYQz55XuiygkNHWiQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:rv+O5i51TJgWCRugXAqa,iv:Qx7Y+tAZOsh5K0uAfCjAiKpi8LaUKuBY0iDOf2my5YU=,tag:PGm7gE8d8BPOnfSrwHeBGA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:HFU04Ow2z6vBs8c0z6x3ybg0TJ4ODcBOKta/VKNdFZHuSaL7,iv:T/ue3nTBJshyOWAjdn/Ybt3z5Lzu6OJI5caFFeki3Zo=,tag:OMlOF8p0s/i/H8KDDxm8AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RXZrR0lEWjREazg0SFBT
            eUZIQkF2ZmpROW4zWVo5TTB3VkNUbnRBaUJjCkIzUTNSTWZFNHdGWjZvMWJ2bm9v
            OUlRVU9GQytxN0YxbVFMY2wxbGpLWDQKLS0tIFJia0Qwb090K3dyV0JEd1pmU2F3
            L0ZvR0ZBeUhsRjR5ckpGdEwvWnEwT3MKSKPuwSTVMnmsuYXCTEgcPztme0xtYHvP
            Y7YtJdZs7ONrhSeNemzILw0BpEhNE4hZUBJrxJmx7k4Zokv+gofMZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T22:38:01Z"
    mac: ENC[AES256_GCM,data:Um8RG8bzeU6frRK+O+8eRtk5KN4kxcv2Wyyo2VECdvGC4c5xWnDF6QKyw93IvRkY5o0pDL7fJ3j0sDVCUo5wUTq9nigvsg9zyxqg798rpClTXioZQ8TydApkM5fDNVclEeEflPBzR4vwapqaPWvP79z281oWdiA77gFchxGg0dU=,iv:QWgH8mnsiX30C4lCZRIX7RqFevGQSjQpgDWH+ghKBYE=,tag:wx9tplssDcVqtD4NpLhmTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
