apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    labels:
        cnpg.io/reload: ""
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ZFInqrNxO42O0cBn,iv:mEKphZaI8ObY379BrV5ptsJvTaQ5M8Z3VLxCbBM7gmY=,tag:Ti0ftz6F3MGODtcHcB7w+Q==,type:str]
    password: ENC[AES256_GCM,data:41M7YSPEsC5bYjpBYkL0bYVQ0olFXxneTRSslm/Q0rcKiXk=,iv:JJwDi1rNaNhkG6HTKbh4Q36VU5LGZbRvo5PUJw8sJmU=,tag:lDl2mBY4RybPnybrGShhTA==,type:str]
    minio-user: ENC[AES256_GCM,data:39VW+2Q+i3wCpQ==,iv:0P7D2iJGc2O6wf8c3t6m6e7SnD4fa1JmcccEvA96ypc=,tag:PT3WkkIgjDaRQ7JmTdUxuA==,type:str]
    minio-pass: ENC[AES256_GCM,data:1yzov01N4XoLHPsRdGSdQqOM0OJcFq8IsFac2g==,iv:B+pLs65/hSFDDR90OiRjQqS5Fs4+gxndr0CA3KGBfU8=,tag:EurrBs6a9LUjfq/socZ++Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYStRY28wckVPN3BSaER6
            ZTVWRDV6QVE4blhqT3F2dE9IVUJFSzlSRHdJCm1rQzE5c2JkTVE0VDVkOTNEU2lO
            aXpJWTZ1UXltK0lLR2J0N2JQK2NPNTQKLS0tIGQzZm41c0xreWdBZEt5MnpRdnhw
            dHVzWFhCeFRoY0ZrQkFrWk8xVDBIa3cKMPPfjXd6PfqTWANfZUYyyTT9AUvnIzo6
            5ff6txp7swnESuQYRCQJnDIJkXYuXux8N3N3XDDEbeBkMYVmwmO9Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-01T07:15:15Z"
    mac: ENC[AES256_GCM,data:j7eUI3qeYg2pt/Js62eAIOPSU6EvylWJC3TSsrw1E10tmSRL/8Mbd9hkMUB+yhbOeDPk5v2d4rKe3bO0NrSSCLyw4TH7a5gSzz9hvD3EMPFuQ2eEVG/YYNGv71y4++4WO4rBHa/esEZ2qsHDz6mEPmPk1rdJjVVcS2SADxFJIeU=,iv:yUxO+ZibyXmHN2+ImvVyHp96ztMZiw/p2gpDAzely28=,tag:ZsORy9TZPdb+dMc18gyZ5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
