apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
type: Opaque
stringData:
  POSTGRES_SUPER_USER: pg-superuser
  POSTGRES_SUPER_PASS: curry-connector-petticoat-pedometer
  minio-user: kubernetes
  minio-pass: ludicrous-unshaved-shakiness-ferocity-retrace-concerned-sappy-line
