---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: snapshot-controller
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      backupTarget: nfs://10.10.10.20:/mnt/Hellabooties/k8s-nfs-storage/longhorn-backups/
