---
data_dir: /vector-data-dir

sources:
  kubernetes_source:
    type: kubernetes_logs
    use_apiserver_cache: true
    pod_annotation_fields:
      container_image: container_image
      container_name: container_name
      pod_labels: pod_labels
      pod_name: pod_name
      pod_annotations: ""
    namespace_annotation_fields:
      namespace_labels: ""
    node_annotation_fields:
      node_labels: ""
  talos_kernel_source:
    type: socket
    mode: udp
    address: 127.0.0.1:12000
  talos_service_source:
    type: socket
    mode: udp
    address: 127.0.0.1:12001


sinks:
  kubernetes:
    type: vector
    compression: true
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6010
    inputs: ["kubernetes_source"]
  talos_service_sink:
    type: vector
    compression: true
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6020
    inputs: ["talos_service_source"]
  talos_kernel_sink:
    type: vector
    compression: true
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6030
    inputs: ["talos_kernel_source"]
