apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:a1y5SMI82V+rHzDVW2j1srhVLLWOhMic9Uki+mVZihQ=,iv:XW3PSmgzozSKbCdyS8Nyu/f3w9u48e0meTb+pzT+ry4=,tag:hTZqVE5Pyr6Ti7qdcijxYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNXdQeWRBQTYyRnA1b1Rn
            c1Uyd2lpR3F2WFFqYVlMVEhTbVMrYlAwMWdJCndudkFpL0hJZ21SN1dYdFRkTDZJ
            YWlZaGRUdklCeWRYZzY5R0RDWEVaYU0KLS0tIGlLb3RSMHNENVBydUJzMWNLOWha
            ZURsb1lhcUdraitpVitId25GaGlTKzAKLrFfH4BZCltV9+ccVsLCNQEjpDo0cY51
            T/BiMz7NkNt3HD1HiZU9nibC0hOPxIIQ5SER6ekEGAYVaX18l4jhUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T02:37:01Z"
    mac: ENC[AES256_GCM,data:XrQ6Qlwo4Op4nCVcWwwzSSQ8MCcyfJzs2tCW0arekQLnsiinWFbQGeBYKiKxWG4UbYOkS6tbUuiMRTsaDs80RbPab55/uCqBcBD5a9GratVsgvT1nZs4TfGTLsVh/+CLvCGQfsY/TE7/3AhSW3zJlKd1FBKDTIA213aIC4SagEI=,iv:EdFSueO2xFGvqqzJpnuLLhP6Yy3FOpygVrWNn6dzWZc=,tag:EVqzlAs2E3YKlRtUD0KWwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
