apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: alertmanager-secret
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:VqimErb4kvZmCmsMOgmCTS8ZiBzE0L9Z5lLmS3im4g350zu+NGF+em9PYYuG5lp5bvCvGvB0q3qYDIf75Zq1ZUYRaBsmmBMUK81gj8caFOlcEPqGXeQLSnvUwzWsM7lCd6ISiHWG+ts66abbpNxBeT4gYjC2+ZEEk0rQHK3lmoktaZq1BgitTvurz98KYfyllDIRRU9E1QY1tBpa/bNDAMtRCx9B4rNLs1rnvWmoFJlxuoBudecmmuySiP+Op2+TazVOMoHlExDLJruBTKQ/K8iIeQXIRNxJGUyaOnptvCurp7VH2kYstW79U1K1EXf25HMgcKjocFzQPZENCxPIc1ismVE4DMSpU1NzXjlY5Dxrtpne0ehh9vSE6Hc45jhG7gr/xFFK82G2g/b5vfoJMgvt7N5pRbvYpS+I38kdkBddOB8rggVFncwfJPO2oweM1EGP2+9yxRqlPD1/w+p4P7LviucptI7pVS4fZ90WGO6f6osHhSb0a1L2NMwYH6N4FXD+1QYqFxb3nAy0nnFwCv+/Ib+DCb/ZbnC0lg8Nlam7PkQSTOhy0o/czMYSiK91FZAOTvYIc9Jj2noCxumSg8TJcj0UQ+HT9I+NGC9aFewnBQT+85EcjB4RAq0LlqcPlpNSk+wzKITk8indDxvD8NlbMt/txOHiQBELmMdXRvgOwEv3WvZFpECFjLVC1R6M0TFxHICjeW+II+IYIPp3FLaOxwGHApcXdLLkWs6R9re2QYm0AR7EKVcnLoCzLl2FyoE7DvYsij1pwweDmIjnaduwCpRl/wSZC2MBIGtd6A1zWKptwxNhdVWRIxSOwb+WiWgOIOT7BBXTNVEnEyEWWRLjUZ2yCc46bQwo4Sy/dBtsvhfIbY7bUFYt8lz1at4Lzk//gDsMUUqA9rY5Q7ZbRRBNCMgJ3hWy8C4M7qKhXrRFv6Gyt4C8BujieL5smzJgqrr8FNOT56mNKUgsevaISOeNNAzPlK75vanoM3ayiN09U2DfMXEI2eQiIM3Q6cMCgmAMI6y6kX+tto+hF91aiafPAU74w89k328c1+3dYJJ0bSebG3GQhvMVB7Kyr4C4naVAoBTz8eXpC6IXlqw+3xPDx1GRBS7qEVMZK4ctCNfq8Pb9dDB3rHW/DaJ+AJ1ANGYaeB5RKEeBUUIf5bVarkSmaQqVrfz6lzrwz6Ptf9qDFcvuQnZH+btUB/W5V6V5wJww1wDQeDLWJeQIeqq9qNv+2hj56aNFWNVJA6repqa/scut+fcjQpKPN3LDMLK4Qyy6BRTmpoonW5fIn2qWag5B3iJubgLEs6wNHgpJ2FF4AT8Ty2m8pLSbJBRazVPDAscv6SOgL341TZkIoyu2yF4kypScoGsZZpCaMIZWMe/opDijII22GcJ+vtWS1qDr6a3XsKztSYlLbRdOJAXof8UQk8ctHkwsHcRnv0Jc3olES80y1vnC+UKMgvjo3NUtKd4nz7+5yBGOmRodhT3PlZXwXBokVIb8BKZ8b9Zy1SPPkH+CP9cQpQ7NEcYhWGLnOk/nyXDNcL7/DNxUZQ1sItfLle1tfQhHc6oKrP8y9BVBl7JSAGAFMKpzwRa4xmpf7wF9CguxTGHyDrHyZ0ml0OLAzKZcHIjwDRLs/S0OOUzz7GI4lYSav/wnwtQxkAZEDktisVm/xDuBsYpSeF/E9VRL0oErLQ1s1kex758Uj6xtMY1qfv1nwQhO1LTsXr94O/3uTWEEeFnK/n/OQkWBJRotDFgSFnUy9jQ8OHEcdE5MiIggsArU/r0hDtXL1QTXH8z/5nHgh2PSe7vHcoraNsQnHP40eLlIriHTtVm/WnGq861M1qqzv4wrcxD62GcbFDSTHR/v9hok+HRNxdFPxlDak1amIdCYaTv197FX7qTclzR4xOUDOM5nqtqarvNyJ0XAFDQ8h8QiOXNk4B42J+mZ7/gddaS4/f8Q9COU2v7BPm1Sty8KCy4o5pu2DF3iU3B2xlpSur8oNPoQWDdzdhW2WSxC0nP+SEHH1UUX/XTqYiPFT2/nsvzWC9Mc/CgvlrLG,iv:gkgEKYUmIV89QvLtyDSMXYc5MDDLif7ZD1UYaVDb5AM=,tag:cwXS63I3BgdvpGVD1OGWpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lsg2agmek2496dy54f0clkk4k2d0sykfv5lt55hrsa8jhq3tgf2qe6dl2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY0Zxd0hjZ2V0TFVRQkk4
            c0lkK1VwRlpOZmZiV2xtd0NVcGRRRFc1a20wCm15a1VUTlJVZ09zcEdSc24yNnFi
            V0JzNTBHQXc4enp1VjlPWmxRbFJhYzAKLS0tIG5KWHdzbWswRmx6b2E4TWdDSW83
            WGExZ3BIdEcxUFBveTFhaXRERitmcTQKpX+Nxjyteaeu7/SewLUwRrRa2G+NGKUT
            yeXAF6oi+k6A9oRCPVL+nCKn+6N1QTB+KxxbO7nFQEkeamhCnLexEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T22:40:49Z"
    mac: ENC[AES256_GCM,data:Fxw4VoBuOW4oHrSHMVpODjuayBzmzIRpu71el5wuMZe5RYciCysSL3F4AiydKjZS1YV0VoG/sGsT2eXPF0gVqKlpX27prvW5orNcS6gHmk1u/zmS2WluC9DXQVk040A07UXw82DkN9myjhY3PonX2gCZirvMS2Ev6hpsQHeJJd4=,iv:guryDXeA0kcflf+mVLFJaGfkmLIpp2eyBPSFTbnRZrg=,tag:I4JEHm7kZ/oZeU1Lp52CqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
