---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-mc-raul"
  namespace: &app "minecraft"
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
    kustomize.toolkit.fluxcd.io/prune: "Disabled"
spec:
  storageClassName: "longhorn"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "20Gi"
