# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kube-prometheus-crds
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
